# 在这里编写springboot的配置信息
server:
  port: 8081
  context-path: /


spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5