# 在这里编写springboot的配置信息
server:
  port: 8080
  context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jason
    username: root
    password: 131025

mybatis:
  #实体类所做包
  type-aliases-package: com.boot.domain
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/*.xml